name: Backend Build and Test

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'openjdk'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test