name: Build and Test React App

on:
  push:
    branches:
      - master
    paths:
      - 'by-react-app/**'

jobs:
  common-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd by-react-app
          npm install

  build:
    needs: common-setup

    steps:
      - name: Build React app
        run: |
          cd by-react-app
          npm run build

  test:
    needs: common-setup

    steps:
      - name: Run tests
        run: |
          cd by-react-app
          npm test
